# **NumPy Arrays & Operations**

**Task:**

Create 1D, 2D, 3D arrays.Perform addition, subtraction, multiplication, division.

Use functions: mean(), sum(), std(), reshape(), arange(), linspace().
Find indices of max/min values.

In [24]:
#1D

import numpy as np

oneD=np.array([55,65,75])
oneD


array([55, 65, 75])

In [25]:
#2D

twoD=np.array([[45,35,25],[85,95,15]])
twoD


array([[45, 35, 25],
       [85, 95, 15]])

In [26]:
#3D

threeD=np.array([[[10,20,30],
                  [40,50,60],
                  [70,80,90]]])
threeD


array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [27]:
#add, sub, multi, div

a=np.array([60,70,80,90,100])
b=np.array([10,20,30,40,50])

#add
a+b

#sub
a-b

#multi
a*b

#div
a/b


array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [35]:
#Functions

np.mean(a)

np.sum(a)

np.std(a)

arange=np.arange(12)
arange

arange.reshape((6,2))

np.min(a)
np.max(a)

lin_space=np.linspace(1,5,5)
lin_space

array([1., 2., 3., 4., 5.])